import type { SolarSolution, CompanyCategory } from './types';

export const companyCategories: CompanyCategory[] = [
  { id: 'cat1', name: 'SunPower' },
  { id: 'cat2', name: 'LG Solar' },
  { id: 'cat3', name: 'Panasonic' },
  { id: 'cat4', name: 'Canadian Solar' },
  { id: 'cat5', name: 'Trina Solar' },
];

export const solarSolutions: SolarSolution[] = [
  {
    id: 'sol1',
    name: 'Maxeon 3 Series Panel',
    company: 'SunPower',
    companyId: 'cat1',
    description: 'High-efficiency residential solar panel known for durability and performance.',
    imageUrl: 'https://placehold.co/600x400.png',
    powerOutput: '400W',
    efficiency: '22.6%',
    features: ['Industry-leading efficiency', '25-year warranty', 'Sleek design'],
  },
  {
    id: 'sol2',
    name: 'NeON R ACe Solar Panel',
    company: 'LG Solar',
    companyId: 'cat2',
    description: 'Premium solar module with integrated microinverter for optimized energy production.',
    imageUrl: 'https://placehold.co/600x400.png',
    powerOutput: '375W',
    efficiency: '21.7%',
    features: ['Built-in microinverter', 'Enhanced performance in low light', 'Robust frame'],
  },
  {
    id: 'sol3',
    name: 'EverVolt EVPV370 Panel',
    company: 'Panasonic',
    companyId: 'cat3',
    description: 'High-performance solar panel with all-black aesthetics and superior temperature coefficient.',
    imageUrl: 'https://placehold.co/600x400.png',
    powerOutput: '370W',
    efficiency: '21.2%',
    features: ['All-black design', 'Triple-guard warranty', 'Excellent heat tolerance'],
  },
  {
    id: 'sol4',
    name: 'HiKu6 CS6W Panel',
    company: 'Canadian Solar',
    companyId: 'cat4',
    description: 'Cost-effective and reliable solar panel for large-scale and residential projects.',
    imageUrl: 'https://placehold.co/600x400.png',
    powerOutput: '545W',
    efficiency: '21.3%',
    features: ['High power output', 'LID/LeTID mitigation', 'Suitable for diverse applications'],
  },
  {
    id: 'sol5',
    name: 'Vertex S Series',
    company: 'Trina Solar',
    companyId: 'cat5',
    description: 'Advanced solar panel technology delivering high power density and aesthetic appeal.',
    imageUrl: 'https://placehold.co/600x400.png',
    powerOutput: '405W',
    efficiency: '21.1%',
    features: ['Multi-busbar technology', 'Half-cut cell design', 'Excellent value'],
  },
  {
    id: 'sol6',
    name: 'Performance 3 Panel',
    company: 'SunPower',
    companyId: 'cat1',
    description: 'Reliable and aesthetically pleasing solar panel for residential use.',
    imageUrl: 'https://placehold.co/600x400.png',
    powerOutput: '335W',
    efficiency: '19.9%',
    features: ['Shingled cell technology', 'Enhanced shade tolerance', 'Durable construction'],
  },
];
