
import type { SolarSolution } from '@/lib/types';
import { baseApi } from './baseApi';

// Inject endpoints into the baseApi
export const solutionsApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getSolutions: builder.query<SolarSolution[], void>({
      query: () => 'solutions', // This will make a GET request to /api/solutions
    }),
    // You can inject other solution-related endpoints here (e.g., getSolutionById, addSolution, etc.)
  }),
  // You can override existing endpoints if needed, though it's usually not recommended
  // overrideExisting: false, 
});

// Export hooks for usage in UI components
// These hooks are automatically generated by RTK Query based on the defined endpoints
export const { useGetSolutionsQuery } = solutionsApi;
